# Generated by Django 3.0.7 on 2020-06-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=50, verbose_name='Apellido')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad de residencia')),
                ('cedula', models.BigIntegerField(unique=True, verbose_name='Cedula')),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.BigIntegerField(verbose_name='Celular')),
                ('monthlyExpenses', models.BigIntegerField(verbose_name='Gastos mensuales')),
                ('availableDays', models.IntegerField(verbose_name='Días disponibles por mes')),
                ('availableHours', models.IntegerField(verbose_name='Horas disponibles por día')),
                ('solicitanteUser', models.CharField(max_length=30, verbose_name='Nombre de usuario')),
                ('solicitantePassword', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('question1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 1')),
                ('question2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 2')),
                ('question3', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 3')),
                ('question4', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 4')),
                ('question5', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 5')),
                ('question6', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 6')),
                ('question7', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 7')),
                ('question8', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 8')),
                ('question9', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 9')),
                ('question10', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 10')),
                ('question11', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 11')),
                ('question12', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 12')),
                ('question13', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 13')),
                ('question14', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 14')),
                ('question15', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 15')),
                ('question16', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 16')),
                ('question17', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 17')),
                ('question18', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 18')),
                ('question19', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 19')),
                ('question20', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pregunta 20')),
                ('twitter', models.CharField(blank=True, max_length=30, null=True, verbose_name='twitter')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
    ]
