# Generated by Django 3.0.6 on 2020-06-02 20:30

from django.db import migrations
def create_data(apps, schema_editor):
    'Crea datos iniciales en rappicrowd para la tabla Solicitante'
    Solicitante = apps.get_model('rappicrowd', 'Solicitante') # apps.get_model(app_label, model_name, require_ready=True)
    Solicitante(firstName="Diego", lastName="Pedraza", city='Cali', cedula=1143838685, birthDate='1991-07-12',
                email='dfbq91@gmail.com', celular=3164151780, monthlyExpenses=500000, availableDays=20,
                availableHours=8, solicitanteUser='diegote', solicitantePassword='micontraseña').save()

class Migration(migrations.Migration):

    dependencies = [
        ('rappicrowd', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]

