# Generated by Django 3.0.6 on 2020-06-16 23:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=256)),
                ('cityCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cityUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countryId', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=256)),
                ('countryCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('countryUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currencyId', models.AutoField(primary_key=True, serialize=False)),
                ('currencyName', models.CharField(max_length=256)),
                ('currencyCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('currencyUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Docutypes',
            fields=[
                ('docutypeId', models.AutoField(primary_key=True, serialize=False)),
                ('docutypeName', models.CharField(max_length=256)),
                ('docutypeCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('docutypeUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevels',
            fields=[
                ('educationLevelId', models.AutoField(primary_key=True, serialize=False)),
                ('educationLevelName', models.CharField(max_length=256)),
                ('educationLevelCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('educationLevelUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('investorCed', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('investorName', models.CharField(max_length=256)),
                ('investorLastName', models.CharField(max_length=256)),
                ('investorCelular', models.CharField(max_length=256)),
                ('investorAddress', models.CharField(max_length=256)),
                ('investorCreatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('investorUpdatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('investorPassword', models.TextField()),
                ('investorEmail', models.CharField(default='None', max_length=256)),
                ('investorBirthday', models.DateField()),
                ('investorCedCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Countries')),
                ('investorCedDocutypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Docutypes')),
                ('investorCityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=256)),
                ('stateCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stateUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stateCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('workerCed', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('workerName', models.CharField(max_length=256)),
                ('workerLastName', models.CharField(max_length=256)),
                ('workerCelular', models.CharField(max_length=256)),
                ('workerAddress', models.CharField(max_length=256)),
                ('workerSpentsPerMonth', models.IntegerField(default=0)),
                ('workerEarningsPerMonth', models.IntegerField(default=0)),
                ('workerLabourHoursPerDay', models.IntegerField()),
                ('workerCreatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('workerUpdatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('workerBirthday', models.DateField()),
                ('workerPassword', models.TextField()),
                ('workerPsychoText', models.TextField(default='None')),
                ('workerLicenseDriver', models.CharField(default='None', max_length=256)),
                ('workerDaysPerWeek', models.IntegerField()),
                ('workerEmail', models.CharField(max_length=256)),
                ('workerTwitter', models.CharField(default='None', max_length=256)),
                ('workerFacebook', models.CharField(default='None', max_length=256)),
                ('workerScore', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('workerCedCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Countries')),
                ('workerCedDocutypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Docutypes')),
                ('workerCityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Cities')),
                ('workerCurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Currencies')),
                ('workerEducationLevelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.EducationLevels')),
                ('workerStateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.States')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorsPerWorkers',
            fields=[
                ('investorPerWorkerId', models.AutoField(primary_key=True, serialize=False)),
                ('investorPerWorkerAmount', models.IntegerField(default=0, null=True)),
                ('investorPerWorkerCreatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('investorPerWorkerUpdatedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('investorPerWorkerCurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Currencies')),
                ('investorPerWorkerInvestorCed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Investors')),
                ('investorPerWorkerWorkerCed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Workers')),
            ],
        ),
        migrations.AddField(
            model_name='investors',
            name='investorStateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.States'),
        ),
        migrations.AddField(
            model_name='cities',
            name='cityCountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Countries'),
        ),
        migrations.AddField(
            model_name='cities',
            name='cityStateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.States'),
        ),
    ]
