# Generated by Django 3.0.6 on 2020-05-29 14:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('countryId', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=256)),
                ('countryCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('countryUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currencyId', models.AutoField(primary_key=True, serialize=False)),
                ('currencyName', models.CharField(max_length=256)),
                ('currencyCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('currencyUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Docutypes',
            fields=[
                ('docutypeId', models.AutoField(primary_key=True, serialize=False)),
                ('docutypeName', models.CharField(max_length=256)),
                ('docutypeCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('docutypeUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevels',
            fields=[
                ('educationLevelId', models.AutoField(primary_key=True, serialize=False)),
                ('educationLevelName', models.CharField(max_length=256)),
                ('educationLevelCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('educationLevelUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=256)),
                ('stateCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stateUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stateCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=256)),
                ('cityCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cityUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cityCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Countries')),
                ('cityStateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.States')),
            ],
        ),
    ]
