# Generated by Django 3.0.6 on 2020-05-30 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rappicrowdContainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('workerCed', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('workerName', models.CharField(max_length=256)),
                ('workerLastName', models.CharField(max_length=256)),
                ('workerCelular', models.IntegerField()),
                ('workerAddress', models.CharField(max_length=256)),
                ('workerSpentsPerMonth', models.IntegerField()),
                ('workerEarningsPerMonth', models.IntegerField()),
                ('workerLabourHoursPerDay', models.IntegerField()),
                ('workerCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('workerUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('workerBirthday', models.DateField()),
                ('workerPassword', models.TextField()),
                ('workerPsychoText', models.TextField()),
                ('workerLicenseDriver', models.CharField(max_length=256)),
                ('workerDaysPerWeek', models.IntegerField()),
                ('workerEmail', models.CharField(max_length=256)),
                ('workerTwitter', models.CharField(max_length=256)),
                ('workerFacebook', models.CharField(max_length=256)),
                ('workerCedCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Countries')),
                ('workerCedDocutypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Docutypes')),
                ('workerCityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Cities')),
                ('workerCurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Currencies')),
                ('workerEducationLevelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.EducationLevels')),
                ('workerStateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.States')),
            ],
        ),
    ]
