# Generated by Django 3.0.6 on 2020-05-30 23:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rappicrowdContainer', '0002_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investors',
            fields=[
                ('investorCed', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('investorName', models.CharField(max_length=256)),
                ('investorLastName', models.CharField(max_length=256)),
                ('investorCelular', models.IntegerField()),
                ('investorAddress', models.CharField(max_length=256)),
                ('investorCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('investorUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('investorPassword', models.TextField()),
                ('investorEmail', models.CharField(max_length=256)),
                ('investorCedCoutryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Countries')),
                ('investorCedDocutypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Docutypes')),
                ('investorCityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Cities')),
                ('investorStateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.States')),
            ],
        ),
    ]
