# Generated by Django 3.0.6 on 2020-05-31 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rappicrowdContainer', '0003_investors'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorsPerWorkers',
            fields=[
                ('investorPerWorkerId', models.AutoField(primary_key=True, serialize=False)),
                ('investorPerWorkerAmount', models.IntegerField()),
                ('investorPerWorkerCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('investorPerWorkerUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('investorPerWorkerCurrencyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Currencies')),
                ('investorPerWorkerInvestorCed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Investors')),
                ('investorPerWorkerWorkerCed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rappicrowdContainer.Workers')),
            ],
        ),
    ]
