# Generated by Django 3.0.6 on 2020-05-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rappicrowdContainer', '0004_investorsperworkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investors',
            name='investorCelular',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workerCelular',
            field=models.CharField(max_length=256),
        ),
    ]
